// The original look: pastel plaster houses under earthy tiled roofs.
// A style kit: every kit has PALETTE_SIZE wall + roof pairs, so a block's color index picks the
// same slot in every style. Kits grow hooks as other styles need to draw things their own way.

import * as THREE from 'three';

// Generated by tools/palette.mjs
const walls = ['#f6f3ec', '#fbe6b3', '#f2c85b', '#fcc28d', '#ff9592', '#ffd9e2', '#b0dfa3', '#83e4d5', '#cce9ff'];
const roofs = ['#c95a37', '#158374', '#474e55', '#af3d36', '#874465', '#624377', '#b17300', '#335189', '#4978a7'];

export default {
  name: 'european',
  palette: { walls, roofs },
  walls: walls.map((c) => new THREE.Color(c)),
  roofs: roofs.map((c) => new THREE.Color(c)),
};
