// The original look: pastel plaster houses under earthy tiled roofs.
// A style kit: every kit has PALETTE_SIZE wall + roof pairs, so a block's color index picks the
// same slot in every style, plus the few pieces it draws its own way:
//   trim, glass: window frames and panes · lattice: wooden lattice over the panes, no arches,
//   shutters or curtains · doors: leaf colors · studded: doors with gold studs under a lintel
//   instead of a fanlight · awnings, stripes: awning colors, striped with white or plain ·
//   lanterns: 'bracket' lamps or 'red' paper lanterns · stoneBridges: walkways over water become
//   granite arch bridges
import * as THREE from 'three';
import { WHITE, WINDOW, DOORS, UMBRELLAS } from '../constants.js';

// Generated by tools/palette.mjs
const walls = ['#f6f3ec', '#fbe6b3', '#f2c85b', '#fcc28d', '#ff9592', '#ffd9e2', '#b0dfa3', '#83e4d5', '#cce9ff'];
const roofs = ['#c95a37', '#158374', '#474e55', '#af3d36', '#874465', '#624377', '#b17300', '#335189', '#4978a7'];

export default {
  name: 'european',
  label: 'European',
  palette: { walls, roofs },
  walls: walls.map((c) => new THREE.Color(c)),
  roofs: roofs.map((c) => new THREE.Color(c)),
  trim: WHITE,
  glass: WINDOW,
  lattice: false,
  doors: DOORS,
  studded: false,
  awnings: UMBRELLAS.slice(0, 3),
  stripes: true,
  lanterns: 'bracket',
  stoneBridges: false,
};
